### ISSUE TITLE
Unable to compile on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by HassanMirza01** [tytso/e2fsprogs#193]
recently i upgraded my OS to Ubuntu 24.04 LTS and now i am not able to compile it.
Previously, i was on Ubuntu 22.04.4 and i can confirm its still building fine on my previous PC with 22.04.4.

GCC used in 22.04.4: 11.4.0
GCC used in 24.04: 13.2.0

Error i encountered on 24.04 is 

`plausible.c: In function ‘check_partition_table’:
plausible.c:132:9: error: unknown type name ‘blkid_probe’
  132 |         blkid_probe pr;
      |         ^~~~~~~~~~~
plausible.c:136:14: warning: implicit declaration of function ‘blkid_new_probe_from_filename’ [-Wimplicit-function-declaration]
  136 |         pr = blkid_new_probe_from_filename(device);`

![image](https://github.com/user-attachments/assets/321f0670-a69c-473b-ae39-f7fd1cc25776)

**Comment by tytso** [comment]
The lib/blkid/blkid.h is probably left over from an older build.   If "make distclean" didn't remove it, try running "git clean -xdf".

**Comment by tytso** [comment]
Building with either the internal blkid or the external system-provided blkid library should work.  But you need to make sure that you arne't using half one and half the other.    Again, this is not an e2fsprogs bug; this is purely a faulty build configuration.

**Comment by tytso** [comment]
Finally, note that the system-provided blkid library has more featuers/functionality than the internally-supplied blkid library.  We include an internal blkid library for use when compiling on NetBSD, FreeBSD, MacOS, and Android.  You can use the internal blkid library on Ubuntu, Debian, Fedora, etc., systems; but there will be some minor things like mke2fs warning before overwriting more exotic file system or partition table, etc., that won't be covered by the internal blkid library.   

Also, you can use a separate build directory (e.g., rm -rf build ; mkdir build ; cd build ; ../configure ; make) which will avoid the sort of problem that you ran into.   The other thing to consider doing is to use "dpkg-buildpackage" to build the e2fsprogs if you are planning on using e2fsorigs on your Ubuntu system.   This will make sure you have the same compile flags and options (including security hardening) that us used for building the official packages for Debian and Ubuntu.    It will also handle making sure that things are built using the correct build dependencies.

If you want to be even more careful in terms of using a hermetic build environment you can use a build chroot using schroot[1], sbuild[2] or git-buildpackage[3] (which is how I build the official release packages for Debian).

[1] https://wiki.debian.org/Schroot
[2] https://wiki.debian.org/sbuild
[3] https://wiki.debian.org/PackagingWithGit
